# .github/workflows/workflow.yml

name: CI workflow

# 1. Workflow Triggers: This workflow runs on push or pull_request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 2. Jobs: A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Docker container to run the job in
    container: python:3.9-slim

    # 3. Steps: A sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Installs project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
          pip install nose coverage spec
          nosetests -v --with-coverage --cover-package=app